backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://primily.netlify.com/

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page" }
          - {
              label: "Home",
              name: "home",
              widget: "object",
              fields:
                [
                  {
                    label: "Slider Images",
                    name: "sliderImages",
                    widget: "list",
                    fields:
                      [
                        { label: "Image src", name: "imageSrc", widget: "image" },
                        { label: "Image alt", name: "imagealt", widget: "string" },
                        { label: "Slider Text", name: "imageText", widget: "text" },
                      ]
                  }
                ]
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/feature/index.md"
        label: "Feature"
        name: "feature"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "feature-page" }
          - {
              label: "Feature",
              name: "feature",
              widget: "object",
              fields:
                [
                  {
                    label: "Feature Body",
                    name: "featureBody",
                    widget: "list",
                    fields:
                      [
                        { label: "Head", name: "head", widget: "string" },
                        { label: "Description", name: "description", widget: "text" },
                        { label: "Icon", name: "icon", widget: "string", required: false }
                      ]
                  }
                ]
            }
      - file: "src/pages/describe/index.md"
        label: "Describe"
        name: "describe"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "describe-page" }
          - {
              label: "Describe",
              name: "describe",
              widget: "object",
              fields:
                [
                  {
                    label: "Cards",
                    name: "cards",
                    widget: "list",
                    fields:
                      [
                        { label: "Head", name: "head", widget: "string" },
                        { label: "Description", name: "body", widget: "markdown" },
                        { label: "Image", name: "image", widget: "image", required: false },
                        { label: "Icon", name: "icon", widget: "string" , required: false }
                      ]
                  }
                ]
            }
      - file: "src/pages/video/index.md"
        label: "Video"
        name: "video"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "video-page" }
          - {
              label: "Video",
              name: "video",
              widget: "object",
              fields:
                [
                  { label: "src", name: "src", widget: "string" }
                ]
            }
      - file: "src/pages/description/index.md"
          label: "Description"
          name: "description"
          fields:
            - { label: "Template Key", name: "templateKey", widget: "hidden", default: "description-page" }
            - {
              label: "Description",
              name: "description",
              widget: "object",
              fields:
                [
                { label: "Main Image", name: "mainImage", widget: "image" },
                { label: "Play Store Image", name: "playstoreImage", widget: "image" },
                { label: "Card Head", name: "cardHead", widget: "string" },
                { label: "Description", name: "description", widget: "string" },
                {
                  label: "Cards",
                  name: "cards",
                  widget: "object",
                  field:
                    {
                      label: "Description List",
                      name: "descriptionlist",
                      widget: "list",
                      fields:
                        [
                        { label: "Description", required: true, name: "description", widget: "text" },
                        { label: "Head", required: false, name: "head", widget: "string" },
                        { label: "Icon", required false, name: "icon", widget: "string" }
                        ]
                    }
                }
                ]
      - file: "src/pages/imagedescription/index.md"
          label: "Description"
          name: "imagedescription"
          fields:
            - { label: "Template Key", name: "templateKey", widget: "hidden", default: "imagedescription-page" }
            - {
              label: "Description",
              name: "mainDescription",
              widget: "object",
              fields:
                [
                { label: "Main Image", name: "mainImage", widget: "image" },
                { label: "Play Store Image", name: "playstoreImage", widget: "image" },
                { label: "Card Head", name: "cardHead", widget: "string" },
                { label: "Description", name: "description", widget: "string" },
                {
                  label: "Cards",
                  name: "cards",
                  widget: "object",
                  field:
                    {
                      label: "Description List",
                      name: "discriptionList",
                      widget: "list",
                      fields:
                        [
                        { label: "Description", required: true, name: "description", widget: "text" },
                        { label: "Head", required: false, name: "head", widget: "string" },
                        { label: "Icon", required false, name: "icon", widget: "string" }
                        ]
                    }
                }
                ]
            }
      - file: "src/pages/appgallery/index.md"
        label: "App Gallery"
        name: "appgallery"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "appgallery-page" }
          - {
              label: "App Galley",
              name: "appGalley",
              required: true,
              widget: "object",
              fields:
                [
                  { label: "App Head", name: "appGalleryHead", widget: "string" },
                  {
                    label: "Slider Images",
                    name: "sliderImages",
                    widget: "list",
                    fields:
                      [
                        { label: "slider Image", name: "slideImg", widget: "image" }
                      ]
                  }
                ]
            }
      - file: "src/pages/pricing/index.md"
        label: "Pricing"
        name: "pricing"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "pricing-page" }
          - {
              label: "Pricing",
              name: "pricing",
              widget: "object",
              fields:
                [
                  { label: "Pricing Head", name: "pricingHead", widget: "string" },
                  { label: "Description 1", name: "description1", widget: "string" },
                  { label: "Description 2", name: "description2", widget: "string" },
                  { label: "Tic Image", name: "ticImage", widget: "image" },
                  {
                    label: "Price Box 1",
                    name: "priceBox1",
                    required: true,
                    widget: "object",
                    fields:
                      [
                        { label: "Head", name: "head", widget: "string" },
                        { label: "Head 2", name: "head2", widget: "string" },
                        { label: "Description", name: "description", widget: "string" },
                        { label: "Price", name: "price", widget: "number" },
                        {
                          label: "Features List",
                          name: "featureList",
                          widget: "list",
                          fields:
                            [
                              { label: "List", name: "list", widget: "string" },
                            ]
                        }
                      ]
                  },
                  {
                    label: "Price Box 2",
                    name: "priceBox2",
                    required: true,
                    widget: "object",
                    fields:
                      [
                        { label: "Head", name: "head", widget: "string" },
                        { label: "Head 2", name: "head2", widget: "string" },
                        { label: "Description", name: "description", widget: "string" },
                        { label: "Price", name: "price", widget: "string" },
                        {
                          label: "Features List",
                          name: "featureList",
                          widget: "list",
                          fields:
                            [
                              { label: "List", name: "list", widget: "string" },
                            ]
                        }
                      ]
                  }
                ]
            }
      - file: "src/pages/demo/index.md"
        label: "Demo"
        name: "demo"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "demo-page" }
          - {
              label: "Demo",
              name: "demo",
              required: true,
              widget: "object",
              fields:
                [
                  { label: "Demo Head", name: "demoHead", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                  {
                    label: "Demo Images",
                    name: "demoImages",
                    required: true,
                    widget: "object",
                    fields:
                      [
                        { label: "Sourse 1", name: "src1", widget: "image" },
                        { label: "Sourse 2", name: "src2", widget: "image" }
                      ]
                  }
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "About Description", name: "aboutDescription", widget: "text" }
          - {
              label: "About Gallery",
              name: "aboutGallery",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Contact Description", name: "contactDescription", widget: "text" }
          - {
              label: "Contact Gallery",
              name: "contactGallery",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/details/index.md"
        label: "Details"
        name: "details"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "details-page" }
          - { label: "Details Title", name: "title", widget: "string" }
          - { label: "Details Description", name: "detailsDescription", widget: "text" }
          - {
              label: "Details Gallery",
              name: "detailsGallery",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "SEO Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/faq/index.md"
        label: "Frequently asked questions"
        name: "faq"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "faq-page" }
          - {
              label: "Frequently asked questions",
              name: "faq",
              widget: "object",
              fields:
                [
                  { label: "Title", name: "faqHead", widget: "string" },
                  {
                    label: "Question and Answers",
                    name: "questionsAndAns",
                    widget: "list",
                    fields:
                      [
                        { label: "Question", name: "question", widget: "string" },
                        { label: "Answer", name: "answer", widget: "text" }
                      ]
                  }
                ]
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
      - file: "src/pages/policy/index.md"
        label: "Policy"
        name: "policy"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "faq-page" }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Policy",
              name: "policy",
              widget: "list",
              fields:
                [
                  { label: "Heading", name: "policyHead", widget: "string", required: false},
                  { label: "Description", name: "policyDescription", widget: "text" }
                ]
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Browser Tab Title", name: "browserTitle", widget: "string"},
                  { label: "Title", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                ],
            }
  - name: "navbarAndFooter"
    label: "Navbar & Footer"
    files:
      - file: "src/pages/footer/index.md"
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "footer" }
          - {
              label: "Logo Image & Tagline",
              name: "logoImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                  { label: "Tagline", name: "tagline", widget: "string" },
                ],
            }
          - {
              label: "Social Links",
              name: "socialLinks",
              widget: "list",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link URL", name: "linkURL", widget: "string" },
                ],
            }
      - file: "src/pages/navbar/index.md"
        label: "Navbar"
        name: "navbar"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "navbar" }
          - {
              label: "Menu Items",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link Type", name: "linkType", widget: "select", options: ["internal", "external"] },
                  { label: "Link URL", name: "linkURL", widget: "string", hint: "Use a relative URL (e.g. /about) if the link is an internal link." },
                ],
            }
